version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      # build the application image
      - run: python -m pip install awscli piprepo
      - run: python -m pip install git+https://github.com/astrofrog/autowheel@edb91267299b0e135486c9df947b24baae68710e
      - run: mkdir -p /tmp/wheelhouse
      # create the wheel
      - run: autowheel linux64 --output-dir /tmp/wheelhouse
      - run: piprepo build /tmp/wheelhouse
      - run: aws s3 cp /tmp/wheelhouse s3://${AWS_BUCKET_NAME}/ --recursive --sse --acl public-read --cache-control max-age=3600,public
      - store_artifacts:
          path: /tmp/wheelhouse


workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
